#%RAML 1.0 NamedExample

value:

    ID: 2 
    code: ER45if
    price: 540.99
    departureDate: 2017/07/27
    origin: SFO
    destination: ORD
    emptySeats: 54
    plane: 
      type: Boeing 777
      totalSeats: 300